### ISSUE TITLE
Close after press generate

### ISSUE THREAD

**Issue by Abdu20222** [LagradOst/QuickNovel#10]
The app works fine before my phone updated to android 11.

The app close after I press generate or click on novel title in library that still not ready to generate Epub.

My phone is Redmi Note 9 Pro.

**Comment by LagradOst** [comment]
So the app caches when you try to generate the epub file and do did nothing else besides pressing generate? AND this started to happend after you updated to android 11 right?

This seams to be the classic case of scoped storage.

**Comment by Abdu20222** [comment]
Yes, also when pressing the novel title in library page that updated to last chapter, but still need to generate Epub file.

**Comment by Abdu20222** [comment]
Any plan to solve this problem.
Since I post this issue I can't generate any Epub.

**Comment by LagradOst** [comment]
And you cant stream read atm? 

Yes I should fix this issue, forgot about it. The next update will fix it.

**Comment by Abdu20222** [comment]
stream read work fine.

**Comment by LagradOst** [comment]
Try now @Abdu20222

**Comment by LagradOst** [comment]
No response, I will close this issue now. Create a new one if the issue still exists.
