### ISSUE TITLE
Issue with provider ranobe

### ISSUE THREAD

**Issue by CloudS33ker** [LagradOst/QuickNovel#102]
Ranobe doesn't load up description pages or download the books.

![Screenshot_20220714-163838](https://user-images.githubusercontent.com/87701610/178969367-16392eca-4958-4044-abc4-3671d5e410ad.png)

**Comment by LagradOst** [comment]
@KillerDogeEmpire

**Comment by Blatzar** [comment]
Fixed in https://github.com/LagradOst/QuickNovel/commit/a1b450ffcff556d75b945407c661f6260b4fee98
