### ISSUE TITLE
[REQ] Searching and Source

### ISSUE THREAD

**Issue by Lustsifer** [LagradOst/QuickNovel#11]
Can you add categories when searching novel by site/source? 

**Example:**
When searching _Death Mage_ then the result from site A will be displayed in the first row, site B in the second row, etc.

**Reference screenshot from TachiyomiSY app:**
![Screenshot_20210709-023736](https://user-images.githubusercontent.com/84452966/124980538-b7323280-e05e-11eb-82fd-09f241b758f6.png)
_The screenshot above is just a reference how my request should be when applied_

**Comment by LagradOst** [comment]
So you simply want the option for search to be ordered by site? Like in the image?

**Comment by Lustsifer** [comment]
Yes, if possible that is. It is more convenient to know which site is it from when enabling multiple search providers and pleasing to the eyes to look at.

**Comment by LagradOst** [comment]
It sure looks nice, however it might take some time for me to add it beavuse of more urgant matters to be added first

**Comment by Lustsifer** [comment]
Take your time. It's not really urgently needed right now.

**Comment by LagradOst** [comment]
![Screenshot_20210812_020009_com.lagradost.cloudstream3.jpg](https://user-images.githubusercontent.com/11805592/129118629-7d996550-4925-47db-97fc-bc19da55013f.jpg) I did this for another app I am making so it will probs be in the next update

**Comment by LagradOst** [comment]
Added this now.
