### ISSUE TITLE
Issue with provider box novel

### ISSUE THREAD

**Issue by CloudS33ker** [LagradOst/QuickNovel#110]
Box novel doesn't show novel art. Instead shows just a white image instead.

![Screenshot_2022-07-28-23-29-29-913_com lagradost quicknovel](https://user-images.githubusercontent.com/87701610/181606236-37cf0374-e366-42f5-9505-49c6dd492bb0.jpg)

**Comment by ArnoldasM** [comment]
I think that the issue is with your device.

 ![Screenshot_20220804_094610_com.lagradost.quicknovel.jpg](https://user-images.githubusercontent.com/77094601/182781640-e5f37d3a-86ae-4138-a076-2d060665e5f3.jpg)

**Comment by CloudS33ker** [comment]
Thanks. I'll try it on other devices
