### ISSUE TITLE
Repository Access Blocked

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/QuickNovel#113]
Dear @lagradost
I am unable to access cloudstream3 repository. It says "Repository Access Blocked". I have never violated any rules. Can you check this please?

**Comment by KillerDogeEmpire** [comment]
@imurreflection can't fix, DMCA took it down. here is the new repo run by @LagradOst's friend or someone
https://github.com/reduplicated/Cloudstream

**Comment by imurreflection** [comment]
DMCA on Repository? I hope this will not have any impact on the application. Thanks for the new link friend
