### ISSUE TITLE
TTS ignores global voice settings

### ISSUE THREAD

**Issue by Oxika95** [LagradOst/QuickNovel#131]
Details: Pixel 2XL Lineage OS Android 12
In Text-to-Speech accessibility settings default/global TTS is set to use Ivona TTS for everything. 

When running the app and using TTS my global TTS settings seem to be ignored. I don't know if google TTS is packaged with the app but low quality voices are being used. Not sure if this is behavior as intended. If it is feature request to allow global settings or voice selection if not a fix would be great!
![Screenshot_20221007-092153_Settings](https://user-images.githubusercontent.com/48342370/194622540-c0625daf-4129-4cd8-9b87-5883b32b1da0.png)

**Comment by willbilec** [comment]
Yes, same issue both on my pixel 5 and s21. On my pixel 5 google Text to Speech is used when I would use Eloquence as my default TTS.
On my Samsung s21 Samsung text-to-speech engine is used even though Google TTS is selected in system settings.
Samsung TTS has an issue where it will pause and play randomly through out whatever it is reading.

**Comment by Oxika95** [comment]
I actually brought this up to the Devs in their discord channel. A dev by the handle null stepped in and helped to work on a fix and even demonstrated the fix in use on their dev build but it so far hasnt been pushed to the live app.

> null — 10/08/2022 4:34 AM
> I should probs fix this
> ye @Oxika95 let me fix
> null — 10/08/2022 7:08 AM
> ![Screenshot_1](https://user-images.githubusercontent.com/48342370/208191720-ad12b618-0c15-46ef-9bce-6a61508623a1.jpg)
> ![Screenshot_2](https://user-images.githubusercontent.com/48342370/208191723-4a3102bc-006f-4675-8610-0cd0af85f8b5.jpg)
> Oxika95 — 10/08/2022 7:32 AM
> I have TTS installed on my phone but I'm not sure if that's what your referring to. But it certainly looks like you have made much more progress than I did. Does the language selection pull from the users installed languages or the google defaults?
> null — 10/08/2022 7:35 AM
> yes, it allows users to select language and voice
> it pulls for avalible TTS
> tts.availableLanguages
> tts.voices

This is a quote from our chat. I would be happy to see the fix implemented soon.
