### ISSUE TITLE
Ranobes provider not working

### ISSUE THREAD

**Issue by trihardseven** [LagradOst/QuickNovel#132]
Tried downloading 5 books from ranobes, all of them stuck at downloading first chapter. Other sources work fine, but ranobes has the freshest chapters and chillest novels.

**Comment by LagradOst** [comment]
iirc they have a lot of antibot stuff, so it is recommended to stream read on that provider

**Comment by trihardseven** [comment]
I see. I use moonreader for TTS so that's not an option for me, ended up using WebToEpub and transfering the files my tablet.
