### ISSUE TITLE
Source Request : Novels.pl

### ISSUE THREAD

**Issue by Lukyzzz** [LagradOst/QuickNovel#138]
https://www.novels.pl/
It's amazing, it even has audio books, web novels etc

**Comment by LagradOst** [comment]
404

**Comment by Lukyzzz** [comment]
![Screenshot_20221030-164444_Chrome.jpg](https://user-images.githubusercontent.com/28473476/198898509-30e4b304-4687-4ef5-99fe-bf68bf60454f.jpg)

**Comment by Lukyzzz** [comment]
> 404

But it's working fine

**Comment by Lukyzzz** [comment]
![Screenshot_20221030-165237_Chrome.jpg](https://user-images.githubusercontent.com/28473476/198898949-f053dae6-48ab-427a-aba0-c6d1330cdc4c.jpg)

**Comment by LagradOst** [comment]
not for me
