### ISSUE TITLE
Regenerate epub feature

### ISSUE THREAD

**Issue by Azuka** [LagradOst/QuickNovel#141]
There is a bug with some novels that causes errors with epubs.

Eg a novel `A` with an epub named `A.epub` will generate `A (1).epub` when new chapters come in. When that happens, the next will be `A (2).epub`.

The only way to fix this is to delete all the `A*.epub` files before generating epubs from new chapters, or to delete and re-add the book before downloading all the chapters and generating the epub.

Is it possible to allow regenerating instead of disabling the current button?

**Comment by Azuka** [comment]
Thanks, any way we can get an option to regenerate?

> this is not a problem with my code, but with android itself. storage is a bitch

**Comment by LagradOst** [comment]
this should have been solved in the latest update

**Comment by Azuka** [comment]
Thank you so much, @LagradOst!
