### ISSUE TITLE
[Bug] Downloads only one chapter

### ISSUE THREAD

**Issue by TitanToast** [LagradOst/QuickNovel#145]
If I try to download a novel, it will only download one chapter of it.
The same happens for every novel if I refresh in the Library tab.

The sources that I use are BoxNovel and FreeWebNovel.

**Comment by killerlearner** [comment]
Did you use steam instead of download as I downloaded currently and it's fine and yeah maybe you make your app in background so it stop working for fixing that you should allow it unrestricted access.

**Comment by TitanToast** [comment]
I tried it with the app in foreground, still the same problem. It also worked perfectly fine with the previous version.

**Comment by killerlearner** [comment]
You should try a vpn or use 1.1.1.1

**Comment by TitanToast** [comment]
I've tried a VPN, sadly still the same issue. I could try a reinstall, but I would loose all my downloaded novels.

**Comment by killerlearner** [comment]
Just copy/cut files folder from android/data/appname and you won't loss anything.

**Comment by TitanToast** [comment]
Can't do that, my device isn't rooted.
![Screenshot_20230107-120433](https://user-images.githubusercontent.com/105084080/211157282-40f43acf-5106-45a7-a6d7-1a6271646484.png)

**Comment by killerlearner** [comment]
If solved how about closing this issue!

**Comment by TitanToast** [comment]
I just tried to reinstall it, sadly still the same issue.

**Comment by TitanToast** [comment]
The previous version 2.1.0 still works fine. 

Oh and it seems that the new version does not ask me for a storage permission. Maybe that's the issue

**Comment by samanta-widjaja** [comment]
it happens to me too, so i downgrade to version 2.1.0

**Comment by samanta-widjaja** [comment]
it happens to me too, so i downgrade to version 2.1.0

**Comment by TitanToast** [comment]
Version 2.3.0 fixes the issue and everything works now perfectly.

Thank you very much!
