### ISSUE TITLE
Interoperability with Tachiyomi extensions.

### ISSUE THREAD

**Issue by rokejulianlockhart** [LagradOst/QuickNovel#157]
This would allow less maintenance of sources, provide a de-facto standard for all e-book software to adhere to, and most importantly, not duplicate effort.

**Comment by LagradOst** [comment]
Tachiyomi is for manga/images this is for text

**Comment by rokejulianlockhart** [comment]
However, surely it also support pictography?

**Comment by LagradOst** [comment]
no, not to such a degree. it is just a patchwork solution

**Comment by rokejulianlockhart** [comment]
Understood, although obviously it'll have to improve in order to allow people to enjoy picture-heavy literature. In which case, I believe that my suggestion should at least eventually be considered.
