### ISSUE TITLE
Interface consistency between projects.

### ISSUE THREAD

**Issue by rokejulianlockhart** [LagradOst/QuickNovel#158]
The interface of this software should be identical to Cloudstream's, because if it is neglected, the differences between the codebases shall merely increase, causing unnecessary duplication of effort merely to maintain standards across LagradOst projects.

Additionally, the interface of this when compared to Cloudstream's is quite obviously inferior – it lacks animations and [a #000000 (OLED) theme](https://github.com/LagradOst/QuickNovel/issues/133) that Cloudstream has possessed for some time.

**Comment by LagradOst** [comment]
dont care about consistency between projects. your reasoning is flawed as I merely borrow what I like from cs3 to qn and what I like about qn to cs3

**Comment by rokejulianlockhart** [comment]
@LagradOst, how is my rationale “flawed”? (The more consistency, the better the UX and the less development time necessary due to differences in the codebases.)

I've only stated this to do good for this software. I believe that you should more sincerely reconsider my rationale.

**Comment by LagradOst** [comment]
no, I know my own projects better than you

**Comment by rokejulianlockhart** [comment]
@LagradOst, indeed. However, did my specific examples not demonstrate some merit to this?
