### ISSUE TITLE
Generated files option

### ISSUE THREAD

**Issue by Abdu20222** [LagradOst/QuickNovel#16]
Can you please add option to overwrite the generated file over the old one. With each update now will be new file generated.

**Comment by LagradOst** [comment]
Wait what??, can you send a ss. Because it is not supposed to do that at all.

**Comment by Abdu20222** [comment]
Now ok, before I delete all files generated by last update, I have this problem, but now ok.

**Comment by LagradOst** [comment]
So is it fixed in the latest ver? yes/no?

**Comment by Abdu20222** [comment]
It start with last update, after I delete both files & novels from library the problem solved.
