### ISSUE TITLE
BoxNovel problem

### ISSUE THREAD

**Issue by Abdu20222** [LagradOst/QuickNovel#17]
There is a problem with BoxNovel see the attached picture, the website work fine.
![Screenshot_2021-09-04-23-20-03-745_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/132107162-68134c2c-6ba9-4362-88ac-f4d356991616.jpg)

**Comment by LagradOst** [comment]
Fixed, same issue as #18

**Comment by Abdu20222** [comment]
There is no search results for BoxNovel in search tab or explore.
Also some novels links not working, as "Super Gene".
![Screenshot_2021-09-05-08-15-55-185_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/132116242-0dfa75d1-7acf-42b4-bcf4-d9d0ca6ae08b.jpg)
![Screenshot_2021-09-05-08-13-41-137_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/132116244-561c635a-c51a-442f-a64d-77817af34126.jpg)
