### ISSUE TITLE
Request update

### ISSUE THREAD

**Issue by SilentO-OPlayer** [LagradOst/QuickNovel#172]
Hi LagradOst, I'll like to know if you are going to update the app soon.

Thanks again for creating this awesome application.

**Comment by LagradOst** [comment]
Will do, just forgor

**Comment by SilentO-OPlayer** [comment]
> Will do, just forgor

Thanks can't wait.

**Comment by LagradOst** [comment]
The app is currently being updated with a new UI. It is not done yet but can be checked out at the branch refactor

**Comment by LagradOst** [comment]
The update was somewhat delayed because I was waiting for pr, but he has not responsed. the UI update will be pushed soon
