### ISSUE TITLE
TTS doesn't work properly 

### ISSUE THREAD

**Issue by somebodywithwings** [LagradOst/QuickNovel#178]
My phone runs miui 14 

After updating to 3.0.0 TTS freezes after 1 or 2 sentences and also skips first words of
 them too.
Tried out Librera's TTS and it worked just fine.

What's the problem?

Okay the problem was my phone 
Sorry

**Comment by LagradOst** [comment]
I quite litterly changed no logic for the tts nor have any of these issues myself. I have legit no idea
