### ISSUE TITLE
Wuxiaworldsite link broken

### ISSUE THREAD

**Issue by CloudS33ker** [LagradOst/QuickNovel#18]
Can't update chapters from wuxiaworldsite. Update causes the list to show zero chapters. Book description page shows no chapters but everything else in the description page is okay.

I've replicated this issue on 2 separate devices, one phone and one tablet. I have also tried to switch wifi networks but the issue persists. 

I have checked if the website is accessible. No problems when accessing website on browser of the same device.

Please look at the screenshots.

![Screenshot_2021-09-05-03-03-17-844](https://user-images.githubusercontent.com/87701610/132108597-3fdafc74-c936-4415-a4d8-12cd18ee9cd6.jpeg)
![Screenshot_2021-09-05-03-02-35-525](https://user-images.githubusercontent.com/87701610/132108604-3571b70e-0219-4fca-baf5-e385ead81dbe.jpeg)

**Comment by LagradOst** [comment]
Fixed, same issue as #17
