### ISSUE TITLE
Freewebnovel not working

### ISSUE THREAD

**Issue by samanta-widjaja** [LagradOst/QuickNovel#180]
I tried to update new chapter cultivation chat group on my downloaded. It fails even on all novel from the same provider. 

https://freewebnovel.com/cultivation-chat-group.html is running fine though

![Screenshot_2023-07-04-01-30-18-524_com lagradost quicknovel](https://github.com/LagradOst/QuickNovel/assets/53214405/798064a0-ed7a-4df1-9053-bce3bbb9bd36)

**Comment by LagradOst** [comment]
Works fine for me

**Comment by samanta-widjaja** [comment]
It's fine on search, but when tries to open novel detail. It show up like the picture on the first post

**Comment by LagradOst** [comment]
I quite litterly opened that link in qn and it worked fine

**Comment by samanta-widjaja** [comment]
It works now. Weird. Thank you
