### ISSUE TITLE
Provide account sync functionality.

### ISSUE THREAD

**Issue by rokejulianlockhart** [LagradOst/QuickNovel#185]
https://github.com/recloudstream/cloudstream/issues/549#issue-1847125505

<blockQuote>

### Describe your suggested feature

Currently, no data added to a user's installation of this application is synchronized between their devices. This makes the current list and watch progress tracking functionality nigh useless if the user uses multiple devices. Consequently, I propose that a synchronization system be developed.

### Other details

https://github.com/recloudstream/cloudstream/pull/128#issuecomment-1675069301

**Comment by LagradOst** [comment]
duplicate

**Comment by rokejulianlockhart** [comment]
> https://github.com/LagradOst/QuickNovel/issues/185#issuecomment-1675573763

Of what?
