### ISSUE TITLE
[bug report][suggestions] few providers are not working as it should

### ISSUE THREAD

**Issue by rpcarvalheira** [LagradOst/QuickNovel#188]
After you select ranobes, it shows its library with all the novels, but whenever you click in any novel, it will get stuck in infinite loading. The website now have a captcha before opening any novel, so it could be the problem.
![Screenshot_20230816_104840_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/2656688d-9f36-4a5a-a572-1026bc7c7216)

Most providers filters are lacking options to filter or simply working less than intended. There is some options available to some providers but not to all of them despite being available in their websites. This feature could get a bit more refined.

Allnovel infinitely repeats the same novels when scrolling
![Screenshot_20230816_104533_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/faeb33ce-457d-4091-97c4-507f73d8ba7a)
![Screenshot_20230816_104539_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/7098f07f-474f-4cb0-8d7c-e3af635dde4d)
![Screenshot_20230816_104545_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/6713543c-34f2-4a97-b8ad-75535484564d)
![Screenshot_20230816_104550_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/d8579557-b0ba-41ad-b2b1-fb476a1e62ca)

Azynovel gives a few errors that will be attached in the print
![Screenshot_20230816_104459_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/c66afb39-f96f-4c9a-b36c-227a08b50f73)

Mtlnovel doesn't show any novels after selecting it to browse.
![Screenshot_20230816_104815_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/60274770/0ee44704-18c3-4da1-a39e-1b4623e28731)

For these, there can be a few suggestions. While the actual method works, one competitor, Shousetsu, makes it different that could help  speed the development of the app in some ways (if possible): it stores those sites and the methods to get the novels in a repository that's in another git and allows users to implement other repos and fixing it faster, since all the things related to repos would have its dedicated space. As well, it helps patch without waiting to merge other things and solve other problems, since everytime you open the app with internet access, it will look to update the repos. Another way could be to try something else with webview or a data scrapper that passes captcha on other sites, since websites like ranobe and webnovel will try to fight against novel apps. But I'm not a developer, so that's just random gambling for what could work.

Another app that works wonders but lacks lots of features (while having others that I envy) is LNReader. The way they implement sources is really some fine work. Would be nice to take a look at their work. What they miss is the direct way to download in epub and open in an external reader directly from the app.

**Comment by LagradOst** [comment]
fixed as of https://github.com/LagradOst/QuickNovel/commit/3bc8b08fe13ef7d447e743578e35a59d40e72b93
`removed RanobesProvider due to capcha`
`added cloudflarekiller to MTLNovel (still not working)`
`fixed NovelFull+AllNovel pages`
`removed Azynovel as it does not exist anymore`

1. bypassing any sort of capcha is not possible even with webview
2. Shousetsu repos use an entirety different backend and not smth I can just add without much work
3. LNReader uses React, I am not even sure if I can those sources
