### ISSUE TITLE
[bug] Ghost downloads on internet loss

### ISSUE THREAD

**Issue by Tim3141** [LagradOst/QuickNovel#189]
I have unstable internet. If I start a download then something interrupts it cancels download and any other download I make results in "ghost" chapters which disappear once I try to read the novel.
This issue happens to all unfinished novel downloads. Whether you started a download for a new novel or updated an old one, if you interrupt it, this happens.
A "fix" to this is to go to streaming chapters and read missing chapters there. After that it will download normally.
This is an old issue I had for a long time with this app. If you have time please fix it, it's slightly annoying.

**Comment by LagradOst** [comment]
fixed in 21cd118a6971f99e7c18248498ab8e37ba834269, wrongly closed #190
