### ISSUE TITLE
There is no search results for BoxNovel.

### ISSUE THREAD

**Issue by Abdu20222** [LagradOst/QuickNovel#19]
There is no search results for BoxNovel in search tab or explore.
Also some novels links not working, as "Super Gene".
![Screenshot_2021-09-05-08-15-13-668_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/132132203-82e64501-7bf6-4f06-acfe-e249569a82c5.jpg)
![Screenshot_2021-09-05-08-13-41-137_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/132132208-a100d7ee-0524-404d-80b6-f609c1682084.jpg)

**Comment by LagradOst** [comment]
Fixed
