### ISSUE TITLE
Quick Novel Not Working In s21 fe

### ISSUE THREAD

**Issue by IchiroAndo** [LagradOst/QuickNovel#190]
I have recently upgraded to an s21 fe and have downloaded quick novel on it. But while streaming a novel works any novel chapter that I download cannot be read, as in it just loads indefinitely after I click on the dove I want to read. Is an issue with where the novels are supposed to be, like are they supposed to be in a separate folder rather than just to download folder?

**Comment by LagradOst** [comment]
I can try

**Comment by LagradOst** [comment]
wait wrong issue

**Comment by LagradOst** [comment]
Streaming a novel works exactly like downloading, so there should not be any difference

**Comment by IchiroAndo** [comment]
> Streaming a novel works exactly like downloading, so there should not be any difference

Hello, thank you for taking the time to look at my issue, but even after deleting then redownloading the application from a new APK this you still seems to happen do you think it's possible that it's having trouble pulling up the files as I did transfer over basically all of the data I had on my other phone? If so do you have any way that I could resolve this issue, other than factory resetting my phone?

**Comment by IchiroAndo** [comment]
> Streaming a novel works exactly like downloading, so there should not be any difference

I figured out that it might have some sort of incompatibility with the backup that I kept on restoring as when I've tried to download and read the epubs from a fresh start with no backup restored I didn't have any noticeable issues.

**Comment by IchiroAndo** [comment]
I think I found the real reason why it wouldn't work. I believe it's due to the app not good with recognizing not the most recent chapter that the user was on was streamed or downloaded and if the users last chapter exceeds the latest downloaded chapter then the app tries searching for files that don't exist on the phone. I believe away a person can resolve this is just by pressing stream novel then going back to something like chapter one if you have downloaded a few chapters recently then checking if it works.
