### ISSUE TITLE
(bug) Infinite loading on redownloading books

### ISSUE THREAD

**Issue by Tim3141** [LagradOst/QuickNovel#193]
If you try to redownload a book that lost chapters, for example royalroadlib book going on Amazon. It will proceed to display a loading circle and do nothing.

I suspect it's something related to the app trying to open a chapter X when there are less chapters in total. This didn't happen in the old versions

**Comment by Tim3141** [comment]
Some clarification: loading looks like this 
![Screenshot_2023-09-14-12-50-29-934_com lagradost quicknovel](https://github.com/LagradOst/QuickNovel/assets/139050650/e86de99d-9d17-4872-b9d9-52b30a416cc3)
And using third party readers is completely fine and has no errors.

**Comment by c-h-u-c-k** [comment]
I took have this problem. Is there any way you could release a patched version? Thanks

**Comment by LagradOst** [comment]
fixed as of https://github.com/LagradOst/QuickNovel/commit/1cce118eeaedba12bf91d3b2fcf9c88b9e4d5aaf
