### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by kodoor** [LagradOst/QuickNovel#204]
When ever I try to refresh all updates on the Download Tab using a swipe down the app crashes straight away..
The only way I can get new chapters is by pressing the refresh button on every novel individually... 
This just happend out of nowhere with no major changes to the device.. 
It might have happend due to a new subscribed novel but I don't know which one..

**Comment by LagradOst** [comment]
smells like too many enties, causing mem or cpu max

**Comment by kodoor** [comment]
> smells like too many enties, causing mem or cpu max

Is their a maximum number that the auto refresh can handle?
All other functions work correctly other than some different sites misbehaving..

**Comment by LagradOst** [comment]
> > smells like too many enties, causing mem or cpu max
> 
> Is their a maximum number that the auto refresh can handle?
> All other functions work correctly other than some different sites misbehaving.. 

There is no set limit, however refreshing does a get request for every entry and that takes both a lot of mem and cpu. how much a device can handle is dependant on how good hardware. I might be able to fix this by rate limiting, but atm it just sounds like out of memory crash

**Comment by LagradOst** [comment]
Should be fixed
