### ISSUE TITLE
Add New Providers

### ISSUE THREAD

**Issue by EHMilon** [LagradOst/QuickNovel#205]
This is a good app for book lover. But why this app only limited Nobel. This app approach should be wide, not only just Nobel any kind of books. It should support .pdf, .epub file extension.
Will you add those providers listed below,
1. Library Genesis 
2. Internet Archive
3. Project Gutenberg

I don't know I am right or wrong. I feel like I should say.

**Comment by LagradOst** [comment]
qn already supports epub and for books check out annas achive. we dont support any form of pdf tho

**Comment by EHMilon** [comment]
> qn already supports epub and for books check out annas achive. we dont support any form of pdf tho

Do you have any Plan to support .pdf file extension? As Cloud Stream 3 offer all most all movies and TV series to watch and download. In this same way, if we can download all books available in Internet using this app, I think it will be the best feature on this app. 

Suppose I need to download “head first java” book. What I have to do, go to the internet and search for “head first java free PDF file download” and after find a website then we can download. But most of the website are broken. 

So please make this app for any kind of books support and add some new provider. If possible.
@LagradOst

**Comment by LagradOst** [comment]
> > qn already supports epub and for books check out annas achive. we dont support any form of pdf tho
> 
> Do you have any Plan to support .pdf file extension? As Cloud Stream 3 offer all most all movies and TV series to watch and download. In this same way, if we can download all books available in Internet using this app, I think it will be the best feature on this app. 
> 
> Suppose I need to download “head first java” book. What I have to do, go to the internet and search for “head first java free PDF file download” and after find a website then we can download. But most of the website are broken. 
> 
> So please make this app for any kind of books support and add some new provider. If possible.
> And if not possible, please close this issue. I Will understand.
> @LagradOst 

there is no plans on supporting pdf atm. we only deal with plain text/html in this app
