### ISSUE TITLE
Can't generate new epub files from downloaded novels

### ISSUE THREAD

**Issue by fairlyamusing** [LagradOst/QuickNovel#211]
I can't seem to generate new .epub files from downloaded novels anymore. The issue seems to have come up just recently, maybe after the latest update. But the thing is that even downgrading the issue still persists. 
Did anyone have anything similar and maybe has a solution?
I've been using the app for what feels like at least 2 years with no problems.
When I click Read Epub button which until now generated a .epub file in my downloads/epub folder, it now always says "Error loading novel". I can still stream read but I used to open the epub in another reader and cant do so anymore.

**Comment by fairlyamusing** [comment]
Fixed the issue by following the steps below.
<img width="710" alt="image" src="https://github.com/LagradOst/QuickNovel/assets/96388514/b1d1df4d-b07d-4645-a413-33cac5c1648e">

**Comment by LagradOst** [comment]
Yes, that is the intended solution. The download shit changed a bit with the latest update so no surprise it stopped working for some because of androids horrible security api.
