### ISSUE TITLE
Broken links with box novel and read light novel 

### ISSUE THREAD

**Issue by CloudS33ker** [LagradOst/QuickNovel#22]
Broken links with the website showing as per screenshots below.

Verified with other devices and networks.

![Screenshot_2021-09-08-02-04-52-311](https://user-images.githubusercontent.com/87701610/132407775-f95acaea-5c07-4fce-830d-f6a7b50b9360.jpeg)
![Screenshot_2021-09-08-02-04-35-929](https://user-images.githubusercontent.com/87701610/132407782-80c4df7f-2712-45ca-aedb-db556bc0566f.jpeg)
![Screenshot_2021-09-08-02-04-21-554](https://user-images.githubusercontent.com/87701610/132407787-0fe6bfa2-cd5d-4264-9a08-b8e4a3acf0c3.jpeg)

**Comment by LagradOst** [comment]
Fixed
