### ISSUE TITLE
Can't download updated chapters

### ISSUE THREAD

**Issue by aoezix** [LagradOst/QuickNovel#226]
So after updating new version, I can't seem to download the latest chapter of particular novel.
![Screenshot_2024-02-11-10-39-02-674_com lagradost quicknovel](https://github.com/LagradOst/QuickNovel/assets/144789279/f66635a4-46b4-4708-be9c-8f6e25912a90)

**Comment by LagradOst** [comment]
Known issue, you can downgrade or wait for the update to fix it
