### ISSUE TITLE
[Bug] Wuxiaworld.site

### ISSUE THREAD

**Issue by Lustsifer** [LagradOst/QuickNovel#23]
WuxiaWorldSite novel cover doesn't appear and when I click download it just stuck with just downloading the first chapter.

I test it with my other device too and the image still doesn't appear but weirdly the download progressing normally in that device.

![Screenshot_20210908-051838](https://user-images.githubusercontent.com/84452966/132418055-8b18374f-5a47-4a0e-9b78-175c1406e29e.png)
![Screenshot_20210908-051905](https://user-images.githubusercontent.com/84452966/132418073-174b83d6-1ab4-4fa4-becb-181baafc2115.png)

**Comment by Zeynex** [comment]
Im having the download issue too

**Comment by LagradOst** [comment]
Fixed
