### ISSUE TITLE
Option to keep downloaded chapters that have been removed from the source

### ISSUE THREAD

**Issue by ka1izer** [LagradOst/QuickNovel#240]
For example, many novels on RoyalRoad are available for a short time before going to Kindle Unlimited. Amazon does not allow books on KU to be freely available other places, which means they have to take down most of the chapters. When I then sync the novel, even if I had those chapters downloaded, they are also removed from QuickNovel. It would be great to have an option or something to avoid this happening. Thanks

**Comment by LagradOst** [comment]
Chapters are never deleted without user action, it might seam like they have 7/7 instead of 1231/7 after sync, but no data is lost until you reload a chapter manually or delete the novel

**Comment by ka1izer** [comment]
But is the data usable? For example, I have one novel that I had the entire "book 1"++ worth of chapters. After most of those were deleted on RoyalRoad, they don't show up in the app. I only have the first 5 chapters or so in the chapter list, and even trying to go from chapter 5 to 6, it goes right to the first "book 2" chapter. 
Is this how it is supposed to behave? Can I do anything to show the "hidden" chapters?
