### ISSUE TITLE
Either internet bug or Download Bug

### ISSUE THREAD

**Issue by trunks132** [LagradOst/QuickNovel#248]
Internet stable but can't download novel, time stays same even how many minutes passed. Novel cover didn't load. Tried several tricks but still no luck.
![Screenshot_20240621_091924](https://github.com/LagradOst/QuickNovel/assets/173423447/cd25aaed-5663-472c-a0b4-980de9e0cf83)
![Screenshot_20240621_091637](https://github.com/LagradOst/QuickNovel/assets/173423447/4a21c351-1faa-4184-8fce-98479558b584)

**Comment by trunks132** [comment]
I just found out, libread site was the problem same goes to freewebnovel. Please fix it, I have many novel in libread

**Comment by SilentO-OPlayer** [comment]
Having the same issue...

**Comment by SummerBoi718** [comment]
Waiting💀

**Comment by raugadh** [comment]
+1

**Comment by SilentO-OPlayer** [comment]
I just downgraded to version 3.1.5 and found out that both freewebnovel and libread work fine on this version.

![Screenshot_20240625-235044_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/63564433/1a612d2b-60ad-4d78-8398-e8ff5af6e121)

![Screenshot_20240625-235049_QuickNovel](https://github.com/LagradOst/QuickNovel/assets/63564433/8312d141-b02f-4dcc-b0e0-4ab7e4e49fe4)

**Comment by vicky18189** [comment]
I have the same issue, I think. I am unable to delete some novels from downloads and can't even open the details page. Error is similar to the 2nd screenshot.

![LOM Unable to delete](https://github.com/LagradOst/QuickNovel/assets/6774564/f5848368-ce1f-4fa6-944e-939d5d09e580)

![LOM Error](https://github.com/LagradOst/QuickNovel/assets/6774564/3581d922-b5dc-4157-b1aa-2945b74a42eb)

**Comment by raugadh** [comment]
Not resolved downloading epub stops after a bit
have to refresh continuously to maintain download.

**Comment by samanta-widjaja** [comment]
the new update resolve it, at least for freewebnovel. i haven't tried the other site
