### ISSUE TITLE
Can't Restore Data from backup

### ISSUE THREAD

**Issue by SilentO-OPlayer** [LagradOst/QuickNovel#251]
Hi LagradOst,

I'm having trouble with restoring data from my backup.
![20240623_211034](https://github.com/LagradOst/QuickNovel/assets/63564433/d65f396b-1af5-4c05-ad28-b1b9ff741ec0)

I can't seem to select anyone of them.

Got any solutions?

**Comment by LagradOst** [comment]
Try renaming to .txt

**Comment by SilentO-OPlayer** [comment]
Thanks, it worked.
