### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [LagradOst/QuickNovel#256]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, the differences to the one provided at your latest release were huge. Was that APK really built from the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

APK diff:

```diff
-------------------------------
--- /dev/fd/63  2024-07-12 00:42:22.657947136 +0200
+++ /dev/fd/62  2024-07-12 00:42:22.661947109 +0200
@@ -1,13 +1,13 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         670a0005
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         f5f4a9c0
+  32-bit CRC value (hex):                         fed3e7f7
   assets/dexopt/baseline.profm
-  32-bit CRC value (hex):                         6c52b629
+  32-bit CRC value (hex):                         32efe8aa
   classes.dex
   32-bit CRC value (hex):                         362edffd
   classes2.dex
-  32-bit CRC value (hex):                         607243bf
+  32-bit CRC value (hex):                         f04b4b36
   DebugProbesKt.bin
   32-bit CRC value (hex):                         7cded4df
   META-INF/CHANGES
@@ -2364,9 +2364,3 @@
   32-bit CRC value (hex):                         1ca1cc7a
   resources.arsc
   32-bit CRC value (hex):                         eb06f860
```

The Dex diff is rather huge (the diff of the `baseline.prof` is rather only its `dex_checksum` field, because of the Dex). I've tried `./gradlew assembleRelease` with JDK 17 and also 11, no dice, the diff remains.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by LagradOst** [comment]
It was built on the same commit and with nothing else added afaik. However I dont follow any of your "clean build rules", for example using JetBrains Runtime (jbr) 17.0.9 or caching, nor do I really care. The same goes with CloudStream 3, but cs3 also contains secret API keys and build-time-generated IDs.

The main platform for qn and cs3 is on github and fdroid is really an afterthought, and as such I dont really bother. If this or any other issue is a critical issue, then you can remove this app and cs3 from fdroid.

**Comment by IzzySoft** [comment]
Thanks for your reply – even though it was not the one we'd hoped for. This was not about F-Droid btw, but about IzzyOnDroid :wink: I won't nag you with this additional security feature then and simply mark your app accordingly to not include it with RB checks. However, should you one day change your mind, be welcome to let us know and we'll look into it again.
