### ISSUE TITLE
Remove Bloat 

### ISSUE THREAD

**Issue by NaeemBolchhi** [LagradOst/QuickNovel#260]
![Screenshot_20240814-171407_Moon+ Reader Pro](https://github.com/user-attachments/assets/690722e9-dcbc-42d7-857b-be711f2cc52f)

This appears for some sources. This instance is from LibRead. Twice or more in every chapter.

I like to save as epub and read with Moon+ Reader. This screenshot is from there.

**Comment by LagradOst** [comment]
This was fixed in c5524d10e217b75ab7b16cc2a297e69bfa9e5546
