### ISSUE TITLE
[Bug] Wuxiaworld.site error.... again.

### ISSUE THREAD

**Issue by Lustsifer** [LagradOst/QuickNovel#29]
I suddenly can't open novel from wuxiaworld.site source today, but I can still access it yesterday.
![Screenshot_20210925-075404](https://user-images.githubusercontent.com/84452966/134752476-11a70ac6-46f4-47a3-9ad6-4b4a1a847906.png)

**Comment by Lustsifer** [comment]
I checked again but the error changed.
![Screenshot_20210925-110138.png](https://user-images.githubusercontent.com/84452966/134757198-678c72da-e90c-4935-a89d-f9087181e0ae.png)

**Comment by LagradOst** [comment]
Bruh

**Comment by Zeynex** [comment]
Yeah both have issues online loades the menu of download or read but doesnt load chapters nor does it download and normal wuxia doesnt load at all anymore ^^'

**Comment by Blatzar** [comment]
Fixed code wise, just waiting for @LagradOst for a release.
