### ISSUE TITLE
[Request] Reading downloaded chapters offline

### ISSUE THREAD

**Issue by Lustsifer** [LagradOst/QuickNovel#30]
Can you add offline read? 
So in the case a provider/source meet an issues we can still read the downloaded chapter. I find it inconvenience that every time a provider/source had an issues I can't read the chapters that I already download before.

And can you make the novel information saved offline too?
So we don't need to load it from internet every time we open it.
![Screenshot_20210925-112035.png](https://user-images.githubusercontent.com/84452966/134757727-3fc243dc-28c5-4ebf-ab08-bee18b9c074b.png)

**Comment by Lustsifer** [comment]
Wait... I seem to still can read it offline, but I need to generate epub first. 

Can you make it so we can still read it even if we didn't generate epub first?

**Comment by LagradOst** [comment]
> 
> 
> Wait... I seem to still can read it offline, but I need to generate epub first.
> 
> Can you make it so we can still read it even if we didn't generate epub first?

Yes, this is because external readers cant take the format I use for streaming novels. Also generate epub is only a one time occurrence and if you have downloaded something then you will only have to re-generate it when it uploads new chapters. I know that this process is very slow for long novels.

What is the reason for the request of "And can you make the novel information saved offline too?".

**Comment by Lustsifer** [comment]
> What is the reason for the request of "And can you make the novel information saved offline too?". 

What I mean is that every time when we open a novel like the screenshot 1 below the information in it _(something like cover, synopsis, title, etc.)_ will be saved so that when we open it again we don't need internet. 
The current behavior is that every time I open a novel in my library offline I always got error _(like screenshot 2)_, I want it to be opened _(like screenshot 1)_ even when my internet connection isn't available.

![Screenshot_20210925-112035.png](https://user-images.githubusercontent.com/84452966/134757727-3fc243dc-28c5-4ebf-ab08-bee18b9c074b.png)
_Screenshot 1_

![Screenshot_20210925-215706.png](https://user-images.githubusercontent.com/84452966/134775893-2e958a73-9ee7-46b3-85ce-a83b1f5746f3.png)
_Screenshot 2_

**Comment by LagradOst** [comment]
Then would not smth like a metadata popup be good enought if it is what you want to do? smth along time lines of https://cdn.discordapp.com/attachments/739288952430657558/891367436551618611/Screenshot_20210925_185527_com.netflix.mediaclient.jpg

**Comment by Lustsifer** [comment]
That can do too. I just need to sometimes read the synopsis again because I kinda forgot it so what you suggested can fulfill it.

**Comment by LagradOst** [comment]
Metadata popups added
