### ISSUE TITLE
request simultaneously chapter download

### ISSUE THREAD

**Issue by Dlordload** [LagradOst/QuickNovel#38]
Is it possible to add an option of being able to download multiple chapters of a novel at a time for better downloading speed

**Comment by LagradOst** [comment]
Yes, however the reason why it is single threaded and (sometimes throttled) is to not trigger any anit-bot protection or DDOS protection. I wont ever change how fast I download, and if I do it is to throttle it more.

Normaly sites only expect a single requests and this app is making like 100/min
