### ISSUE TITLE
crashes if colon in title

### ISSUE THREAD

**Issue by michinoke** [LagradOst/QuickNovel#4]
version: 1.4.7 (fdroid)

Downloading works fine but app crashes when you press generate epub.

If you reopen the app, go to 'My Downloads' and attempt to open the book it will crash again.

Examples:

* https://www.royalroad.com/fiction/41618/mark-of-the-fool-a-progression-fantasy
* https://www.royalroad.com/fiction/42385/an-outcast-in-another-world-subtitle-is-insanity

**Comment by LagradOst** [comment]
Hmmmm, I had a similar problem with another one of my apps, it seams that some android versions have a bugged File creator. I will fix this in the next update

**Comment by LagradOst** [comment]
@michinoke try the latest update, it should be fixed 👍

**Comment by michinoke** [comment]
Completely fixed with 1.5.0. QuickNovel has really improved my reading experience btw, thanks.
