### ISSUE TITLE
Trailer.to issue 

### ISSUE THREAD

**Issue by xaviQ7** [LagradOst/QuickNovel#49]
Developer of cloudstream I am trying to watch Spider-Man no way
home and when I watch it from the website trailer.to it just shows a 15 second video no movie. I would appreciate if you could fix this

**Comment by LagradOst** [comment]
1. Wrong repo this is quicknovel
2. It means that it does not exist

**Comment by xaviQ7** [comment]
Thanks I appreciate the quick reply
