### ISSUE TITLE
[bug] When I enter Arabic sources, the novels do not appear to me

### ISSUE THREAD

**Issue by xkingxn** [LagradOst/QuickNovel#55]
![Screenshot_٢٠٢٢٠١٢٦-١٦٥٣٥٨](https://user-images.githubusercontent.com/89549795/151175677-adbb4254-32d8-4b09-99d2-4008f6168d0c.png)
![Screenshot_٢٠٢٢٠١٢٦-١٦٥٣٥٠](https://user-images.githubusercontent.com/89549795/151175685-e21f512d-a135-4b38-9b36-c2c7d67f28f3.png)

**Comment by LagradOst** [comment]
Both providers added anti scraping
