### ISSUE TITLE
readnovelfull

### ISSUE THREAD

**Issue by Abdu20222** [LagradOst/QuickNovel#58]
All ReadNovelfull novels chapters are 0/0 in the app, but not in website.
![Screenshot_2022-02-05-21-56-03-515_com lagradost quicknovel](https://user-images.githubusercontent.com/87010741/152655071-b0f8464c-f1a3-49a6-8be1-8de19fe71eeb.jpg)

**Comment by knightmob** [comment]
Yes me tooo

**Comment by LagradOst** [comment]
they added antibot, `Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.` and also ip ban
