### ISSUE TITLE
Enable ttl playback at the same time as other apps 

### ISSUE THREAD

**Issue by persov** [LagradOst/QuickNovel#62]
An option to allow ttl to continue reading even when another app is playing can be Helpful, at least I come across it a lot. 

It's best if it's a switch so we can decide when to turn on the feature. 

Thank you so much for all the work you put into the project!

**Comment by LagradOst** [comment]
Ye, quicknovels tts does not stop when you go into other apps. The problem is that your phone wants to save battery so it pauses the tts service and there is nothing I can do. You have to disable battery optimization for both quicknovel and google talk service for it to properly work while using other apps. Even with this android decides so sometimes delay the response on tts so it may be delayed.

**Comment by persov** [comment]
I do not think that is the case, even after I have done what you said, this behavior continued. 
On the other hand, in other apps (e.g. wabu), even when I did nothing the ttl never stopped. 
I wants to also point out that it does not look like a force stop, it is not that the app freezes, it is as if I pressed the stop button, and if I press it again, the other app stops. 

I would greatly appreciate if you could look into the matter again.

**Comment by LagradOst** [comment]
I can 1000% assure you that the app does not pause tts when you go out of the app. IT only pauses if you play other media, pause via headphones or pause via notification or app UI. all the logic is here https://github.com/LagradOst/QuickNovel/blob/master/app/src/main/java/com/lagradost/quicknovel/ReadActivity.kt and there is no reference to onUserLeaveHint, onUserInteraction or onPause.

**Comment by Lustsifer** [comment]
I think what persov want is for QuickNovel tts to still play even when he play it together with other media like music and video.

I also personally would like this kind of feature in QuickNovel too.

**Comment by LagradOst** [comment]
@Lustsifer If that is the case, then check out https://github.com/LagradOst/QuickNovel/blob/master/app/src/main/java/com/lagradost/quicknovel/ReadActivity.kt#L456 I have no plans on making this an option
