### ISSUE TITLE
Request Added French translation option for ebooks 

### ISSUE THREAD

**Issue by LeenaDanvers** [LagradOst/QuickNovel#63]
Hi! I Just discovered your app set and they are really awesome so thank you so much for sharing them with us My request concerns the language, Can you add the ebook translation option please. I'm French , I'm very passionate about the app but unfortunately there's no way for me to read the stories in English, so having the French translation option would be really really helpful and it will encourage more downloads of the application and therefore the opening to the French community.

 I don't know if that's how applying on this site works, I hope that's understandable and if not. I'm sorry.

**Comment by LagradOst** [comment]
Sorry, but non english sources wont be added by me. It is not as simple as just adding an url and it works. If you really want a french site added then the fastest way is to make a pull request yourself.
