### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by Recoil1024** [LagradOst/QuickNovel#8]
Great you gave online reading option but pls add bookmark option as well

**Comment by LagradOst** [comment]
That was the plan I had when I added online reading, but I wanted to get the update out because I am working on smth else on another app. 

The next update will have bookmark system split up into: Reading, Plan to Read, Paused and Dropped that you can access from the library tab.

**Comment by zaIsBa** [comment]
it's would be awesome if u could name em your self like u have the option to create different "categories" then u can add the webnovel in whichever one u desire

**Comment by LagradOst** [comment]
@zaIsBa I can do that, however I feel like that is not nesessary and wont do it 😔

**Comment by zaIsBa** [comment]
oh ok I can see how it's not necessary but it's helpful, as for me I have at least 5 categories, Reading, Completed, Downloaded, dropped, planning to read and so on however I can try working with three so it's fine :^)

**Comment by LagradOst** [comment]
I will close this issue because the feature is now implemented, if you feel like it should change create a new issue 👍
