### ISSUE TITLE
Issues with text to speech.

### ISSUE THREAD

**Issue by willbilec** [LagradOst/QuickNovel#97]
I have found some issues with TTs.
1. the text to speech speed is extremely fast and there seems there's no way to slow it down. I have tried editing tts settings but same result.
2. You can only use google text to speech. If you disable google text to speech to force a different engine to be used an error will be shown.

**Comment by LagradOst** [comment]
I use the TTS provided by android, so all the settings should transfer over to quicknovel. I have no problem changing the voice, speed or any other setting in the android settings.

**Comment by Dohko1** [comment]
Sorry for not making a new post but since its kinda related I thought it would be better to just comment here. Any chance to add sleep timer to tts? I wake up during midnight when I use it when going to sleep xD

**Comment by LagradOst** [comment]
should have been solved in latest update.

@Dohko1 no sleep timer wont be added
