### ISSUE TITLE
Customize Epub

### ISSUE THREAD

**Issue by wruizcanal** [LagradOst/QuickNovel#98]
I would like to be able to customize the epubs that the app creates.  For example: The size and style of the Title of the chapters.

I also have to check since some epubs do not show the title of the chapters and only show the content.  It is not known in which chapter we are.

Ejem: https://freewebnovel.com/esper-harem-in-the-apocalypse.html

It is also necessary to add the cover, synopsis and other information in the epub.

**Comment by LagradOst** [comment]
1. Too much work for such a niche feature
2. I dont want to encourage people to steal other peoples work reupload them. So if I do this, I will only allow the changing of UI elements, but not metadata (such as name or author)
